routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::delete('/carts/empty','CartController@empty')->name('carts.empty'); 

Route::post('/transactions/paypal','TransactionController@create_paypal_payment'); 

// Route::resource('categories', 'CategoryController'); 
	Route::get('/categories/create', 'CategoryController@create')->name('Categories.create'); 
	Route::get('/categories', 'CategoryController@index')->name('Categories.index'); 
	Route::post('/categories/create', 'CategoryController@store')->name('Categories.store'); 
	Route::get('/categories/{id}', 'CategoryController@show')->name('Categories.show'); 
	Route::get('categories/{id}/edit', 'CategoryController@edit')->name('Categories.edit'); 
	Route::patch('categories/{id}/', 'CategoryController@update')->name('Categories.update'); 
	Route::delete('/categories/{id}', 'CategoryController@destroy'); 

Auth::routes();



Route::get('/home', 'HomeController@index')->name('home');


// Route::get('/products/create', 'ProductController@create'); 
// Route::get('/products', 'ProductController@index');

Route::resource('products', 'ProductController'); 
Route::resource('carts', 'CartController'); 
Route::resource('transactions', 'TransactionController'); 







// 	Route::get('/products/create', function () {
//     return view('Products.create');
// });

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use App\Product;

class CartController extends Controller
{
   /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function index()
   {

       if(Session::has('cart')) {
           // get all the id of cart session
           $product_ids = array_keys(Session::get('cart'));

           // query to the database
           // get all products that are in the session cart
           $products = Product::find($product_ids);

           $total = 0;
           foreach($products as $product) {
               $product->quantity = Session::get("cart.$product->id");
               $product->subtotal = $product->quantity * $product->price;
               $total += $product->subtotal;
           }

           // dd($products);

           return view('carts.index')
               ->with('products',$products)
               ->with('total',$total);
       } else {
           return view('carts.index');
       }
       // return "This is from carts index";

       
   }

   /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function create()
   {
       //
   }

   /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
   public function store(Request $request)
   {
       //
   }

   /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function show($id)
   {
       //
   }

   /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function edit($id)
   {
       //
   }

   /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function update(Request $request, $id)
   {
       // $cart = [
           // id => qty,
           // id => qty
       // ]
       $request->validate([
           'quantity' => 'required|min:1'
       ]);

       $qty = $request->quantity;
       $request->session()->put("cart.$id", $qty);
       
       return redirect( route('carts.index') );
   }

   /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function destroy(Request $request, $id)
   {
       $request->session()->forget("cart.$id");

       if (count($request->session()->get('cart')) == 0) 
       {
           $request->session()->forget("cart");
       }

       return redirect( route('carts.index'))->with('status', 'Product removed from cart');
    }
    public function empty()
    {
       Session::forget('cart');

       return redirect( route('carts.index'))->with('status','Cart Cleared');

   }
}

resources/views/carts/index.blade.php
@extends('layouts.app')


@section('content')
<script src="https://www.paypal.com/sdk/js?client-id=AQSmcK2Aoknk-WOBddqWktY2nz5YlYGF6ntu8s0FjVIi0e2xyupAZACbSAqi3OFSsI05dmDKUzFq9Phj"></script>
{{-- 	{{ dd($request ?? ''->session()->get('cart'))}} --}}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h3>My Cart</h3>
			</div>
			@if(Session::has('status'))
				<div class="col-12">
					<div class="alert alert-success">
						{{ Session::get('status')}}
					</div>
				</div>
			@endif

			
		@include('products.errors')

			@if(Session::has('cart'))
			

		{{-- 			table --}}
			<div class="col-12">
				<div class="table table-responsive"> 
					<table class="table table-striped table-hover text-center">
								<thead>
									
									<th scope="col">Name</th>
									<th scope="col">Price per Unit</th>
									<th scope="col">Quantity</th>
									<th scope="col">Subtotal</th>
									<th scope="col">action</th>
								</thead>
												<tbody>
														@foreach($products as $product)
							{{-- start of row --}}
																	<tr>
																		
																		<th scope="row">{{ $product->name }}</th>
																		<td>&#8369; <span> {{ $product->price }}</span></td>
																		<td>
																			<div class="add-tocart-field mb-1">
																				<form action="{{ route('carts.update',['cart'=>$product->id])}}" method="post">
																					@csrf
																					@method('PUT')
																					<input
																						type="number"
																						name="quantity"
																						id="quantity"
																						class="form-control"
																						value="{{$product->quantity}}"
																						min="1"
																					>
																					<button
																						class="btn btn-outline-secondary w-100"
																						type-"submit"
																					>Edit
																					</button>
																				</form>
																			</div>

																		</td>

																				<td>
																					&#8369; {{ number_format($product->subtotal,2) }}
																				</td>
																				<td>
																	{{-- 	<form action="{{route('carts.destroy'), ['carts'=> $product->id]}}" method="post">
																						@csrf
																						@method('DELETE')
																						
																					<button class="btn btn-danger w-100">Remove From Carts
																					</button>
																				</form> --}}
																				</td>
																
																    </tr>
																@endforeach
												</tbody> 
																	<tfoot>
																			<tr>
																				
																				<td colspan="3" class="text-right">Total</td>
																				<td>&#8369; {{ number_format($total ?? '' ?? '',2) }} </td>	
																				 <td>
																							<form action="{{ route('transactions.store')}}" method="post">
																							
																							@csrf
																							<button class="btn btn-primary w-100">Checkout</button>
																							</form>

																							<div id="paypal-btn"></div>
																							</td>
																			</tr>
																	</tfoot>
								</table>
							</div>
									<form action="{{ route('carts.empty')}}" method="post">	
											@csrf
											@method('DELETE')
	                                     <button type="submit" class="btn btn-outline-danger">Clear Cart</button>
                                 	</form>
               </div>
               @else
               	<div class="col-12">
               		<div class="alert alert-info">
               			Cart Empty
               		</div>
               	@endif 
               	</div>
		</div>
	</div>



<script>
paypal.Buttons({
   createOrder: function(data, actions) {
     // This function sets up the details of the transaction, including the amount and line item details.
     return actions.order.create({
       purchase_units: [{
         amount: {
           value: {{ $total ?? '' }}
         }
       }]
     });
   },
   onApprove: function(data, actions) {
     // This function captures the funds from the transaction.
     return actions.order.capture().then(function(details) {
       // This function shows a transaction success message to your buyer.
       alert('Transaction completed by ' + data.orderID);
       let csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');

       let data = {transactionCode : data.orderID}

       fetch("route for paypal payment",{
       	method : 'post',
       	body: JSON.stringify(data),
       	headers : { 'X-CSRF-TOKEN' : csrfToken }
       })
       .then( response=> response.json())
       .then (res => console.log(res)); 
   });
   }
 }).render('#paypal-btn');
</script>

@endsection