routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::delete('/carts/empty','CartController@empty')->name('carts.empty'); 

Route::post('/transactions/paypal','TransactionController@create_paypal_payment'); 

// Route::resource('categories', 'CategoryController'); 
	Route::get('/categories/create', 'CategoryController@create')->name('Categories.create'); 
	Route::get('/categories', 'CategoryController@index')->name('Categories.index'); 
	Route::post('/categories/create', 'CategoryController@store')->name('Categories.store'); 
	Route::get('/categories/{id}', 'CategoryController@show')->name('Categories.show'); 
	Route::get('categories/{id}/edit', 'CategoryController@edit')->name('Categories.edit'); 
	Route::patch('categories/{id}/', 'CategoryController@update')->name('Categories.update'); 
	Route::delete('/categories/{id}', 'CategoryController@destroy'); 

Auth::routes();



Route::get('/home', 'HomeController@index')->name('home');


// Route::get('/products/create', 'ProductController@create'); 
// Route::get('/products', 'ProductController@index');

Route::resource('products', 'ProductController'); 
Route::resource('carts', 'CartController'); 
Route::resource('transactions', 'TransactionController'); 







// 	Route::get('/products/create', function () {
//     return view('Products.create');
// });

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use App\Product;
use App\Status; 
use Illuminate\Http\Request;
use Str;
use Auth;
use Session;

class TransactionController extends Controller
{
   /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function index()
   {
       $statuses = Status::all();
       // if(auth::user()->role_id==1){
       $transactions = Transaction::all();
        // } else 
        // {
        //   $transactions = Transaction::all()->whereIn('user_id', Auth::user()->id); 
        // }
       return view('transactions.index')
           ->with('transactions', $transactions)
           ->with('statuses', $statuses);
   }

   /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function create()
   {
       //
   }

   /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
   public function store(Request $request)
   {
       // Transaction table
           // Transaction code
           // user_id
       $transaction = new Transaction;
       $transaction->user_id = Auth::user()->id;
       $transaction->transaction_code = Auth::user()->id . Str::random(10);

       $transaction->save();

       // dd($transaction->id);

       // $cart = [
       //     id => qty,
       //     id => qty
       // ]

       $product_ids = array_keys(Session::get('cart'));
           // $product_ids = [id,id];
       $products = Product::find($product_ids);
       $total = 0;
       foreach ($products as $product){
           $product->quantity = Session::get("cart.$product->id");
           $product->subtotal = $product->price * $product->quantity;
           $total += $product->subtotal;

           $transaction->products()
               ->attach(
                   $product->id, 
                   [
                       "quantity" => $product->quantity, 
                       "subtotal" => $product->subtotal,
                       "price" => $product->price

                   ]
               );
       }

       $transaction->total = $total;
       $transaction->save();

       Session::forget("cart");

       // pivot table
           // product_id
           // transaction_id
           // quantity
           // subtotal

       return redirect( route('transactions.show',['transaction'=>$transaction->id])); 
     }

   /**
    * Display the specified resource.
    *
    * @param  \App\Transaction  $transaction
    * @return \Illuminate\Http\Response
    */
   public function show(Transaction $transaction)
   {
       $statuses = status::all(); 
       return view('transactions.show')
              ->with('transaction', $transaction)
              ->with('statuses', $statuses); 
   }

   /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Transaction  $transaction
    * @return \Illuminate\Http\Response
    */
   public function edit(Transaction $transaction)
   {
       //
   }

   /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Transaction  $transaction
    * @return \Illuminate\Http\Response
    */
   public function update(Request $request, Transaction $transaction)
   {
     $transaction->status_id = $request->status;
     $transaction->save();
     return redirect( route('transactions.index')); 
   }

   public function destroy()
   {
    //
   }
   public function create_paypal_payment(Request $request)
   {
     $galing_sa_fetch = json_decode($request->getContent(), true); 
     return ["message" => $galing_sa_fetch];  
   }

  }

resources/views/transactions/includes/table-transaction.blade.php
<table class="table table-striped">
	<tbody>

		<tr>
			<td>Customer Name:</td>
			<td>{{ $transaction->user->email }}</td>
		</tr>


		<tr>
			<td>
			Transaction Code
			</td>
			<td>
			{{ $transaction->transaction_code }}
			</td>
		</tr>

		<tr>
			<td>
			Payment mode:
			</td>
			<td>
			{{ $transaction->payment_mode->name}}
			</td>
		</tr>

		<tr>
			<td>
			Date of Purchase
			</td>
			<td>
			{{ $transaction->created_at->format('F d, Y h:i:s') }}
			</td>
		</tr>

		<tr>
			<td>
			Status
			</td>
		<td>
				{{ $transaction->status->name }}

				<form action="{{ route('transactions.update', ['transaction'=>$transaction->id])}}" method="post">
				@csrf
				@method('PUT')

				<select name="status" id="status" class="form-control">

					@foreach($statuses as $status)
						<option value="{{$status->id}}" {{$transaction->status_id == $status->id ? 'selected':''}}>
						{{$status->name}}
						</option>
					@endforeach

				</select>

			<button class="btn btn-warning">Edit Status</button>
			</form>

		</td>
	</tr>
	</tbody>
</table>
<hr>
{{-- end of transaction table --}}

{{-- {{dd($transaction->products)}} --}}

{{-- start of table product_transaction --}}
	<table class="table table-striped table-hover">

	<thead>
		<th scope="row">Product Name</th>
		<th scope="row">Price</th>
		<th scope="row">Quantity</th>
		<th scope="row">Subtotal</th>
	</thead>

<tbody>
{{-- start of product-transaction details --}}
		@foreach($transaction->products as $transaction_product)
				<tr>
					<td>
					{{$transaction_product->name}}
					</td>

					<td>
					&#8369; {{ number_format($transaction_product->pivot->price,2) }}
					</td>

					<td>
					{{$transaction_product->pivot->quantity}}
					</td>

					<td>
					&#8369; {{ number_format($transaction_product->pivot->subtotal,2) }}
					</td>
				</tr>
		@endforeach
{{-- end of product-transaction details --}}
</tbody>

	<tfoot>
		<tr>
			<td colspan="3" class="text-right"><strong>Total</strong></td>
			<td>&#8369; {{ number_format($transaction->total,2) }}</td>
		</tr>
	</tfoot>
</table>