routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::delete('/carts/empty','CartController@empty')->name('carts.empty'); 

Route::post('/transactions/paypal','TransactionController@create_paypal_payment'); 

// Route::resource('categories', 'CategoryController'); 
	Route::get('/categories/create', 'CategoryController@create')->name('Categories.create'); 
	Route::get('/categories', 'CategoryController@index')->name('Categories.index'); 
	Route::post('/categories/create', 'CategoryController@store')->name('Categories.store'); 
	Route::get('/categories/{id}', 'CategoryController@show')->name('Categories.show'); 
	Route::get('categories/{id}/edit', 'CategoryController@edit')->name('Categories.edit'); 
	Route::patch('categories/{id}/', 'CategoryController@update')->name('Categories.update'); 
	Route::delete('/categories/{id}', 'CategoryController@destroy'); 

Auth::routes();



Route::get('/home', 'HomeController@index')->name('home');


// Route::get('/products/create', 'ProductController@create'); 
// Route::get('/products', 'ProductController@index');

Route::resource('products', 'ProductController'); 
Route::resource('carts', 'CartController'); 
Route::resource('transactions', 'TransactionController'); 







// 	Route::get('/products/create', function () {
//     return view('Products.create');
// });

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function category()
   {
   	return $this->belongsTo('App\Category');
   }
 }

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category; 
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

         $filter = $request->query('category');
       if($filter){
           $products = Product::all()->whereIn('category_id', $filter);
       } else {
           $products = Product::all();
       }

       // dd($request->query('category'));
       return view ('products.index')
           ->with('products', $products)
           ->with('categories', Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('products.create')->with('categories', $categories); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'price' => 'required|numeric',
            'category-id' => 'required',
            'description' => 'required|string',
            'image' => 'required|image|max:5000'
        ]); 

        $product = new Product;
        $product->name = $request->input('name');
        $product->price = $request->input('price');
        $product->category_id = $request->input('category-id');
        $product->description = $request->input('description');

        $product->image = $request->image->store('products'); 

        $product->save(); 

        return redirect( route('products.index')); 
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        
        return view('products.show')->with('product', $product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        return view ("products.edit", compact('product'))->with('categories', $categories); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'name' => 'required|string',
            'price' => 'required|numeric',
            'category-id' => 'required',
            'description' => 'required|string',
            'image' => 'image|max:5000'
        ]); 

 
        $product->name = $request->input('name');
        $product->price = $request->input('price');
        $product->category_id = $request->input('category-id');
        $product->description = $request->input('description');

        if($request->hasFile('image')){
        $product->image = $request->image->store('products'); 
        }
        $product->save(); 

        $request->session()->flash('status', 'Update Successful'); 

        return redirect( route('products.edit',['product'=>$product->id])); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
      
        $product->delete(); 

        return redirect(route('products.index'))->with('status','Product is Deleted');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')
@section('content')
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-8 mc-auto">
					<h3>Create Product Form</h3>
						<hr>
						<form action="{{ route('products.store')}}" method="post" enctype="multipart/form-data">
						@csrf

								<input type="text" name="name" id="name" class="form-control mb-2" placeholder="Product Name" value="{{ old('name') }}">
								@if($errors->has('name'))
								<div class="alert alert-danger">
								{{ $errors->first('name')}}
								</div>
								@endif

								<input type="text" name="price" id="price" class="form-control mb-2" placeholder="Price" value="{{ old('price') }}">
								@if($errors->has('price'))
								<div class="alert alert-danger">
								{{ $errors->first('price')}}
								</div>
								@endif

								<select name="category-id" id="category-id" class="custom-select mb-2">
								@foreach($categories as $category)
								<option value="{{ $category->id }}" 
								{{ old('category-id') == $category->id ? "selected" : ""}}>
								{{ $category->name }}
								</option>
								@endforeach
								</select>
								@if($errors->has('category-id'))
								<div class="alert alert-danger">
								{{ $errors->first('category-id')}}
								</div>
								@endif

								<input type="file" name="image" id="image" class="form-control-file mb-2">
								@if($errors->has('image'))
								<div class="alert alert-danger">
								{{ $errors->first('image')}}
								</div>
								@endif

								<textarea name="description" id="description" class="form-control mb-3" cols="10" rows="5" placeholder="Product Description">{{ old('description') }}</textarea>
								@if($errors->has('description'))
								<div class="alert alert-danger">
								{{ $errors->first('description') }}
								</div>
								@endif

		<button type="submit" class="btn btn-primary">Create New Product</button>
		</form>
		</div>
		</div>
</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('content')
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-8 mx-auto">
					<h3>Edit Product Form</h3>
						<hr>
						@if(Session::has('status'))
							<div class="alert alert-success">{{ Session::get('status')}}</div>
						@endif
						<form action="{{ route('products.update', ['product'=>$product->id])}}" method="post" enctype="multipart/form-data">
						@csrf
						@method('PATCH')

								<input type="text" name="name" id="name" class="form-control mb-2" placeholder="Product Name" value="{{ $product->name }}">
								@if($errors->has('name'))
								<div class="alert alert-danger">
								{{ $errors->first('name')}}
								</div>
								@endif

								<input type="text" name="price" id="price" class="form-control mb-2" placeholder="Price" value="{{ $product->price }}">
								@if($errors->has('price'))
								<div class="alert alert-danger">
								{{ $errors->first('price')}}
								</div>
								@endif

								<select name="category-id" id="category-id" class="custom-select mb-2">
								@foreach($categories as $category)
								<option value="{{ $category->id }}" 
								{{ old('category-id') == $category->id ? "selected" : ""}}>
								{{ $category->name }}
								</option>
								@endforeach
								</select>
								@if($errors->has('category-id'))
								<div class="alert alert-danger">
								{{ $errors->first('category-id')}}
								</div>
								@endif

								<input type="file" name="image" id="image" class="form-control-file mb-2" value="{{ $product->image }}">
								@if($errors->has('image'))
								<div class="alert alert-danger">
								{{ $errors->first('image')}}
								</div>
								@endif

								<textarea name="description" id="description" class="form-control mb-3" cols="10" rows="5" placeholder="Product Description">{{ $product->description }}</textarea>
								@if($errors->has('description'))
								<div class="alert alert-danger">
								{{ $errors->first('description') }}
								</div>
								@endif

		<button type="submit" class="btn btn-success">Save Updates</button>
		</form>
		</div>
			<div class="col-12 col-md-4 mx-auto">
					<img src="/storage/{{ $product->image}}" alt="..." class="card-img-top">
							<div class="card-body">
								<h3> {{ $product->name }}</h3>
								<p class="card-text">&#8369; {{ number_format($product->price,2) }}</p>
									<p class="card-text">{{ $product->category->name }}</p>
									<p class="card-text">{{ $product->description }}</p>
							</div>

			</div>
		</div>

</div>
@endsection

resources/views/products/errors.blade.php
@if ($errors->any())
	<div class="alert alert-danger col-12">
		<ul>
			
			@foreach($errors->all() as $error)
			 <li>{{ $error }}</li>
			 @endforeach
		</ul>
	</div>
@endif

resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')

	<div class="container">

 <div class="row">
			<div class="col-12">
				<form action="" method="get">
				@csrf
					<div class="row">
					<div class="col">
						<select name="category" id="category" class="form-control">
							<option value="">All</option>
								@foreach($categories as $category)
								<option value="{{ $category->id }}">{{ $category->name }}</option>
								@endforeach
							</select>
							</div>
							<div class="col">
						<button class="btn btn-outline-primary">Filter</button>
						</div>
					</div>
				</form>
				</div>
			</div>
<div class="row">


		<div class="row">

			@foreach($products as $product)
			{{-- start of cards --}}
				<div class="col-12 col-md-4 col-lg-3">
					<div class="card">
						<img src="/storage/{{ $product->image}}" alt="..." class="card-img-top">
							<div class="card-body">
								<h5 class="card-title">{{ $product->name }}</h5>
									<p class="card-text">&#8369; {{ number_format($product->price,2) }}</p>
									<p class="card-text">{{ $product->category->name }}</p>
									<p class="card-text">{{ $product->description }}</p>
							</div>
									<div class="card-footer">
									<form action="{{ route('carts.update', ['cart'=>$product->id])}}" method="post">
											@method('PUT')
											@csrf
										<input type="number" name="quantity" id="quantity" class="form-control" mb-1 min="1">
										<button class="btn btn-outline-primary w-100 mb-2">Add to Cart</button>
									</form>
										<a href="{{ route('products.show',['product' => $product->id])}}" class="btn btn-outline-success w-100 mb-2">View Product</a>
										<a href="{{ route('products.edit',['product' => $product->id])}}" class="btn btn-outline-warning w-100 mb-2">Edit Product</a>

										<form action="{{ route('products.destroy',['product' => $product->id])}}" method="post">
										@csrf
									@method('DELETE')
									<button type="submit" class="btn btn-outline-danger w-100 mb-2">Delete Product</button>
							</form>
						</div>
					</div>
				</div>
		{{-- end of cards --}}
		@endforeach
		</div>
	</div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
	@section('content')

@if($product)

	<div class="container">
		<div class="row">
			{{-- start of cards --}}
				<div class="col-12 col-md-4 col-lg-3">
					<div class="card">
						<img src="/storage/{{ $product->image}}" alt="..." class="card-img-top">
							<div class="card-body">
								<h3> {{ $product->name }}</h3>
								<p class="card-text">&#8369; {{ number_format($product->price,2) }}</p>
									<p class="card-text">{{ $product->category->name }}</p>
									<p class="card-text">{{ $product->description }}</p>
							</div>

							<div class="card-footer">
										<form action="{{ route('carts.update', ['cart'=>$product->id])}} method="post">
											@csrf
											@method('PUT')
											<input type="number" name="quantity" id="quantity" class="form-control" mb-1 min="1">
											<button class="btn btn-outline-primary w-100 mb-2">Add to Cart</button>
										</form>


											<a href="{{ route('products.edit',['product' => $product->id])}}" class="btn btn-outline-warning w-100 mb-2">Edit Product</a>

										<form action="{{ route('products.destroy',['product' => $product->id])}}" method="post">
										@csrf
									@method('DELETE')
									<button type="submit" class="btn btn-outline-danger w-100 mb-2">Delete Product</button>
							</form>

							</div>



								@else
								 
								 	404 not Found 

								@endif 

					</div>
				</div>
		</div>
	</div>




@endsection